# Lesson 3.4: Make Classes
# Mini-Project: Movies Website

# In this file, you will define instances of the class Movie defined
# in media.py. After you follow along with Kunal, make some instances
# of your own!

# After you run this code, open the file fresh_tomatoes.html to
# see your webpage!

import media
import fresh_tomatoes

new_jack_city = media.Movie("New Jack City", "A crime lord ascends to power and becomes megalomaniacal while a maverick police detective vows to stop him.","Drug tycoon Nino Brown (Wesley Snipes) and his minions, known collectively as the Cash Money Brothers, have rapidly risen to the top of the New York City narcotics trade. Under Nino's heartless leadership, the drug operation has grown into a multimillion-dollar empire. Scotty (Ice-T) and Nick (Judd Nelson), two police officers who know their way around the streets of Harlem, aim to bring Nino and his cohorts down. To do so, though, they'll have to play by Nino's rules and go undercover.", "https://upload.wikimedia.org/wikipedia/en/e/e4/New_jack_city.jpg", "https://www.youtube.com/watch?v=CXrTXaKr0x4")

boyz_n_the_hood = media.Movie("Boyz N The Hood", "Follows the lives of three young males living in the Crenshaw ghetto of Los Angeles, dissecting questions of race, relationships, violence and future prospects.", "Tre (Cuba Gooding Jr.) is sent to live with his father, Furious Styles (Larry Fishburne), in tough South Central Los Angeles. Although his hard-nosed father instills proper values and respect in him, and his devout girlfriend Brandi (Nia Long) teaches him about faith, Tre's friends Doughboy (Ice Cube) and Ricky (Morris Chestnut) don't have the same kind of support and are drawn into the neighborhood's booming drug and gang culture, with increasingly tragic results.", "https://upload.wikimedia.org/wikipedia/en/c/c3/Boyz_n_the_hood_poster.jpg", "https://www.youtube.com/watch?v=AE4BdijGtu4")

menace_ii_society = media.Movie("Menace II Society", "A young street hustler attempts to escape the rigors and temptations of the ghetto in a quest for a better life.","After growing up in the gang lifestyle of the Los Angeles projects, 18-year-old Caine Lawson (Tyrin Turner) wants a way out. Everyone around him, including his unpredictable friend O-Dog (Larenz Tate), is trapped in their lives of crime and violence. With the help of his caring teacher (Charles Dutton) and supportive girlfriend (Jada Pinkett), Caine plans to leave the city for good. But in a series of tragic events, Caine realizes that escape will not be easy.", "https://image.tmdb.org/t/p/original/lstD3oZoNReyKdx6PXfTiBsUkKQ.jpg", "https://www.youtube.com/watch?v=XrMCRkTRmiY")

hustle_and_flow = media.Movie("Hustle & Flow","With help from his friends, a Memphis pimp in a mid-life crisis attempts to become a successful hip-hop emcee." ,"DJay (Terrence Howard) is a pimp living day to day on the tough streets of Memphis, Tennessee. Pushing 40, he's tired of the life he's living and dreams of something greater. When he meets up with an old friend who is now in the recording industry, he's inspired to turn his life around and uses his criminal life as an inspiration to create rap music. When he hears that a rap superstar is coming to town, Djay works a hustle to gain the rapper's attention and hopefully get signed by a label.", "https://upload.wikimedia.org/wikipedia/en/e/e9/Hustle_and_flow.jpg", "https://www.youtube.com/watch?v=99wyHFRng7g")

juice = media.Movie("Juice", "Four inner-city teenagers get caught up in the pursuit of power and happiness, which they refer to as - the juice.","Four Harlem friends -- Bishop (Tupac Shakur), Q (Omar Epps), Steel (Jermaine Hopkins) and Raheem (Khalil Kain) -- dabble in petty crime, but they decide to go big by knocking off a convenience store. Bishop, the magnetic leader of the group, has the gun. But Q has different aspirations. He wants to be a DJ and happens to have a gig the night of the robbery. Unfortunately for him, Bishop isn't willing to take no for answer in a game where everything's for keeps.", "https://upload.wikimedia.org/wikipedia/en/c/ca/Juice_Poster.jpg", "https://www.youtube.com/watch?v=QsWto8p7t1E")

set_it_off = media.Movie("Set It Off","Desperation drives four inner-city women (Queen Latifah, Jada Pinkett Smith, Vivica A. Fox, Kimberly Elise) to bank robbery in Los Angeles, then they start mistrusting one another." ,"After being fired from her job as a bank teller, Frankie (Vivica A. Fox) begins working at a janitorial service with her friends Tisean (Kimberly Elise), a single mother; Cleo (Queen Latifah), a boisterous lesbian; and Stony (Jada Pinkett), who is dealing with the recent death of her brother. The women are struggling with their finances, so they decide to start robbing banks. At first the group is successful, but they soon attract the attention of an obsessive detective (John C. McGinley).", "https://upload.wikimedia.org/wikipedia/en/0/0d/Set_it_off_poster.jpg", "https://www.youtube.com/watch?v=41wGIgx5lT8")

friday = media.Movie("Friday", "Two homies, Smokey and Craig, smoke a dope dealer's weed and try to figure a way to get the $200 they owe to the dealer by 10 p.m. that same night. In that time, they smoke more weed and get jacked and shot at in a drive-by.","It's Friday and Craig Jones (Ice Cube) has just gotten fired for stealing cardboard boxes. To make matters worse, rent is due, he hates his overbearing girlfriend, Joi (Paula Jai Parker), and his best friend, Smokey (Chris Tucker), owes the local drug dealer money -- and that's all before lunch. As the hours drag on, Jones and Smokey experience the gamut of urban life, complete with crackheads, shoot-outs and overly sexual pastors, concentrated into one single, unbelievable Friday.", "https://upload.wikimedia.org/wikipedia/en/2/27/Fridayposter1995.jpg", "https://www.youtube.com/watch?v=nH1Ulp4PBtA")

poetic_justice = media.Movie("Poetic Justice","In this film, we see the world through the eyes of main character Justice, a young African-American poet. A mail carrier invites a few friends along for a long overnight delivery run." ,"Still grieving after the murder of her boyfriend, hairdresser Justice (Janet Jackson) writes poetry to deal with the pain of her loss. Unable to get to Oakland to attend a convention because of her broken-down car, Justice gets a lift with her friend, Iesha (Regina King) and Iesha's postal worker boyfriend, Chicago (Joe Torry). Along for the ride is Chicago's co-worker, Lucky (Tupac Shakur), to whom Justice grows close after some initial problems. But is she ready to open her heart again?", "https://upload.wikimedia.org/wikipedia/en/e/e2/Poetic_Justice_%281993_movie_poster%29.jpg", "https://www.youtube.com/watch?v=pJSBjlQNSuA")

booty_call = media.Movie("Booty Call","Two friends who have gone too long without sex set out to get some." ,"Rushon (Tommy Davidson) is sexually pent-up and ready to take thing things to the next level with his girlfriend, Nikki (Tamala Jones). But when he calls for a date, she asks to make it a double -- bringing along her brash friend Lysterine (Vivica A. Fox), whom Rushon sets up with his lewd buddy, Bunz (Jamie Foxx). Things go better than expected. As the evening transitions from the restaurant to the bedroom, the two men go on a madcap search for what will surely make the night complete: condoms.", "https://upload.wikimedia.org/wikipedia/en/d/d7/Booty_call_poster.jpg", "https://www.youtube.com/watch?v=RopRbjny-W0")

movies = [new_jack_city, boyz_n_the_hood,  menace_ii_society, hustle_and_flow, juice, set_it_off, friday, poetic_justice, booty_call]
fresh_tomatoes.open_movies_page(movies)
